sudo: true
language: node_js
node_js:
- '9'
cache: npm
install:
- npm i
script:
- npm run lint-fix  
- npm run lint
- npm run test
- npm install -g gemini
- npm install -g selenium-standalone
- selenium-standalone install
- selenium-standalone start
- npm run gemini-update
- npm run gemini-test
before_deploy:
- npm run build
- echo "Initializing deployment..."
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GH_TOKEN
  keep-history: true
  local-dir: ./dist
  on:
    branch: master
after_deploy:
- echo "Deployment complete"